# Generated by Django 4.0.6 on 2022-07-27 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='drugs',
            field=models.ManyToManyField(related_name='drugs', to='recipe.drug'),
        ),
    ]
